# Generated by Django 2.2.11 on 2020-04-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200403_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipient_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_shift', to='website.shift'),
        ),
    ]
