# Generated by Django 2.2.11 on 2020-04-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hours',
        ),
    ]
