# Generated by Django 2.2.11 on 2020-04-03 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateField()),
                ('date_end', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('shiftID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Roles')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.schedule')),
            ],
        ),
    ]
