# Generated by Django 2.2.11 on 2020-04-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
