# Generated by Django 2.2.11 on 2020-04-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_hours'),
        ('website', '0002_schedule_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
